name: Angular CI

on:
  push:
    branches: [main, homolog, develop]
  pull_request:
    branches: [main, homolog, develop]

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --immutable --immutable-cache --check-cache

      - name: Unit tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test:unit

      - name: E2E tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test:e2e

      - name: Lint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
